# Generated by Django 5.2.4 on 2025-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PRO', 'SweatPro'), ('ATHLETE', 'SweatAthlete')], default='ATHLETE', max_length=10),
        ),
    ]
