# Generated by Django 5.2.4 on 2025-08-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_profile_picture_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
