# Generated by Django 5.2.4 on 2025-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sweatsheet_assigned_to_sweatsheet_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PRO', 'SweatPro'), ('ATHLETE', 'SweatAthlete'), ('SWEAT_TEAM_MEMBER', 'SweatTeamMember')], default='ATHLETE', max_length=20),
        ),
    ]
